name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2

    - name: Setup do NodeJS
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 16.13.2
      
        
